// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_domination_graph
LogicalMatrix make_domination_graph(IntegerMatrix pspace, IntegerVector list_oc_ids);
RcppExport SEXP Onion_make_domination_graph(SEXP pspaceSEXP, SEXP list_oc_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type pspace(pspaceSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type list_oc_ids(list_oc_idsSEXP);
    __result = Rcpp::wrap(make_domination_graph(pspace, list_oc_ids));
    return __result;
END_RCPP
}
