# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_domination_graph <- function(pspace, list_oc_ids) {
    .Call('Onion_make_domination_graph', PACKAGE = 'Onion', pspace, list_oc_ids)
}

binary_search_closest <- function(vec, val) {
    .Call('Onion_binary_search_closest', PACKAGE = 'Onion', vec, val)
}

